// ============================================================
// Desmake — Shared Data Layer (MVP seed data + helpers)
// ============================================================

// M2: 真实供应链成本来自 src/lib/pricing.ts（附件《中国供应链AI商品平台报价与定价清单》）
import {
  SKU_BY_ID,
  type FamilyId,
  type Region,
  costCents as skuCostCents,
  retailCents as skuRetailCents,
  salePriceCents as skuSaleCents,
  orderFreightUSD as skuOrderFreightUSD,
} from "@/lib/pricing";

// M3: 把定价引擎的公共符号从 data 层再导出，UI/API 只需从 "@/lib/data" 单点引入。
export { SKU_BY_ID, PRODUCT_SKUS, FAMILY_LABELS } from "@/lib/pricing";
export type { FamilyId, Region, ProductSku, WeightClass } from "@/lib/pricing";

/** M3: 发布时创作者勾选的具体商品（SKU）+ 可选 variant（尺寸/颜色/机型）。 */
export type SelectedProduct = { sku: string; variant?: string };

export type Adapter = {
  id: string;
  name: string;
  mockup: string;
  method: string;
  lead: string;
  /** M2: 映射到 pricing.ts 的 6 大商品 family（print3d 适配器的 family 为 home，因附件无 3D SKU） */
  family: FamilyId;
  /** M2: 由 pricing.ts 引擎实时计算（不再写死） */
  costCents: number;
  retailCents: number;
  icon: string;
};

/**
 * 6 大类 family → 该 family 的“代表性默认 SKU”。
 * 用于：未做 SKU 级选择时的基准报价（M4/M5 将允许用户在 43 个 SKU 中任选）。
 * 选择原则：取该 family 中最具代表性、且与适配器名称最贴合的 SKU。
 */
export const FAMILY_DEFAULT_SKU: Record<FamilyId, string> = {
  tshirt: "apparel-tee",        // T恤纯棉圆领
  poster: "wallart-poster-a4",  // 海报 A4
  card: "office-notebook",       // 笔记本 A5（纸品文具代表）
  phonecase: "digital-phonecase",// 手机壳
  sticker: "office-stickersheet",// 不干胶贴纸套装
  home: "home-mug",             // 马克杯（原 print3d 适配器归入 home）
};

/** family 基准出厂成本（cents，来自真实供应链） */
export function costForFamily(f: FamilyId): number {
  return skuCostCents(SKU_BY_ID[FAMILY_DEFAULT_SKU[f]]);
}
/** family 基准建议零售价（cents，税前，含运费×1.15，来自真实供应链） */
export function retailForFamily(f: FamilyId): number {
  return skuRetailCents(SKU_BY_ID[FAMILY_DEFAULT_SKU[f]]);
}
/** 适配器 → family → 默认 SKU id */
export function adapterDefaultSku(id: string): string | undefined {
  const f = adapterById(id)?.family;
  return f ? FAMILY_DEFAULT_SKU[f] : undefined;
}

export type Creator = {
  handle: string;
  name: string;
  city: string;
  role: string;
  verified: boolean;
  followers: number;
  sales: number;
  works: number;
  rating: number;
  bio: string;
  avatarHue: number;
};

export type Design = {
  id: string;
  slug: string;
  seed: string;
  title: string;
  creator: string;
  category: string;
  adapters: string[];
  /**
   * Creator premium in cents, added on top of the adapter base price.
   * This is a real input to `unitPriceCents` — not a separate display price.
   */
  premiumCents: number;
  /**
   * Derived "from" price = base adapter retail + premium (no variant selected).
   * Always computed from the pricing formula; never hand-authored.
   */
  priceCents: number;
  likes: number;
  views: number;
  sales: number;
  rating: number;
  reviews: number;
  aiGenerated: boolean;
  isNew: boolean;
  tags: string[];
  created: string;
  // visual seed for the SVG art generator
  palette: [string, string, string];
  shape: number;
  /** Real AI image URL when the design was generated by the AI provider. */
  imageUrl?: string;
  /** Creator-supplied copy (uploaded designs). */
  description?: string;
  /** "ai" = generated in Studio; "upload" = creator supplied their own image. */
  source?: "ai" | "upload";
  // ── M3: 商品配置与创作者分成 ──
  /** 创作者分成比例 0.10–0.50；缺省表示未配置（下单时按 0 处理，不产生分成） */
  royaltyRate?: number;
  /** 发布时勾选的具体商品（SKU）；缺省时由 adapters 推导 family 默认 SKU（兼容旧数据） */
  selectedProducts?: SelectedProduct[];
};

// M2: costCents/retailCents 由 pricing.ts 引擎实时计算（不再写死）。
// family 映射到 6 大商品类别；print3d 适配器归入 home family（附件无 3D SKU）。
export const ADAPTERS: Adapter[] = [
  { id: "tshirt", name: "T-Shirt", mockup: "tshirt", method: "DTG / DTF", lead: "3–5", family: "tshirt", costCents: costForFamily("tshirt"), retailCents: retailForFamily("tshirt"), icon: "shirt" },
  { id: "poster", name: "Poster", mockup: "poster", method: "Giclée Print", lead: "2–4", family: "poster", costCents: costForFamily("poster"), retailCents: retailForFamily("poster"), icon: "frame" },
  { id: "card", name: "Business Card", mockup: "card", method: "Digital Offset", lead: "3–6", family: "card", costCents: costForFamily("card"), retailCents: retailForFamily("card"), icon: "card" },
  { id: "phonecase", name: "Phone Case", mockup: "phonecase", method: "UV Printing", lead: "3–5", family: "phonecase", costCents: costForFamily("phonecase"), retailCents: retailForFamily("phonecase"), icon: "phone" },
  { id: "sticker", name: "Sticker Pack", mockup: "sticker", method: "Die Cut", lead: "2–3", family: "sticker", costCents: costForFamily("sticker"), retailCents: retailForFamily("sticker"), icon: "sticker" },
  { id: "print3d", name: "3D Print", mockup: "print3d", method: "FDM / SLA", lead: "5–9", family: "home", costCents: costForFamily("home"), retailCents: retailForFamily("home"), icon: "cube" },
];

/**
 * Strict adapter lookup. Returns `undefined` for an unknown id.
 *
 * R2/C4: this used to fall back to `ADAPTERS[0]` (T-Shirt, $32.00), which meant a
 * malformed or mislabelled adapter identifier was silently priced as a T-Shirt —
 * 5 of the 6 adapters charged the wrong amount. Never re-introduce a fallback here;
 * pricing callers MUST handle `undefined` explicitly.
 */
export const adapterById = (id: string): Adapter | undefined => ADAPTERS.find((a) => a.id === id);

/** Display-only helper: adapter name, or the raw id when it is not a known adapter. */
export const adapterName = (id: string): string => adapterById(id)?.name ?? id;

export const CATEGORIES = [
  { id: "all", name: "All", count: 24220 },
  { id: "abstract", name: "Abstract", count: 4820 },
  { id: "typography", name: "Typography", count: 3140 },
  { id: "geometric", name: "Geometric", count: 2760 },
  { id: "illustration", name: "Illustration", count: 5210 },
  { id: "minimal", name: "Minimal", count: 3890 },
  { id: "retro", name: "Retro", count: 1930 },
  { id: "botanical", name: "Botanical", count: 1480 },
  { id: "3d", name: "3D & Objects", count: 990 },
];

const RAW_CREATORS: Array<Omit<Creator, 'avatarHue'>> = [
  { handle: "kaisu", name: "Kai Sugimoto", city: "Kyoto, JP", role: "3D Designer · AI Creator", verified: true, followers: 24800, sales: 3120, works: 48, rating: 4.9, bio: "Generative forms and quiet geometry. Building objects that feel inevitable." },
  { handle: "lenaost", name: "Lena Østergaard", city: "Copenhagen, DK", role: "Graphic Designer", verified: true, followers: 18240, sales: 2410, works: 62, rating: 4.8, bio: "Swiss grids, Nordic light. Type-led compositions for print." },
  { handle: "marcotv", name: "Marco Tavares", city: "Lisbon, PT", role: "Illustrator", verified: false, followers: 9120, sales: 880, works: 31, rating: 4.7, bio: "Hand-drawn chaos, digitally tamed." },
  { handle: "amaraok", name: "Amara Okafor", city: "Lagos, NG", role: "AI Creator", verified: true, followers: 31600, sales: 4870, works: 74, rating: 4.9, bio: "Afro-futurist pattern systems. Prompted, curated, refined." },
  { handle: "yuwen", name: "Yu Wen", city: "Shanghai, CN", role: "Artist · Printmaker", verified: true, followers: 15380, sales: 1960, works: 40, rating: 4.8, bio: "Ink, risograph, and the space between." },
  { handle: "noahb", name: "Noah Brandt", city: "Berlin, DE", role: "Type Designer", verified: false, followers: 7640, sales: 610, works: 22, rating: 4.6, bio: "Letterforms as architecture." },
  { handle: "sofiar", name: "Sofia Ruiz", city: "Mexico City, MX", role: "Illustrator · Muralist", verified: true, followers: 21050, sales: 2740, works: 55, rating: 4.9, bio: "Colour first, always." },
  { handle: "elifk", name: "Elif Kaya", city: "Istanbul, TR", role: "3D Designer", verified: false, followers: 11470, sales: 1290, works: 28, rating: 4.7, bio: "Parametric objects for the home." },
];

export const CREATORS: Creator[] = RAW_CREATORS.map((c, i) => ({ ...c, avatarHue: (i * 47 + 12) % 360 }));
/** Strict lookup — returns `undefined` for an unknown handle (no silent fallback). */
export const creatorByHandle = (h: string): Creator | undefined => CREATORS.find((c) => c.handle === h);

const PALETTES: Array<[string, string, string]> = [
  ["#ff4d18", "#0c0c0d", "#f7f6f3"],
  ["#2244ff", "#1f7a4d", "#f1efea"],
  ["#6b3df5", "#ff4d18", "#f7f6f3"],
  ["#b57500", "#0c0c0d", "#f1efea"],
  ["#1f7a4d", "#0c0c0d", "#f7f6f3"],
  ["#ff4d18", "#b57500", "#f7f6f3"],
  ["#2244ff", "#f7f6f3", "#0c0c0d"],
  ["#0c0c0d", "#f7f6f3", "#ff4d18"],
];

const RAW_DESIGNS: Array<[string, string, string, string[]]> = [
  ["Signal Decay", "kaisu", "abstract", ["poster", "tshirt", "sticker"]],
  ["Meridian 04", "lenaost", "geometric", ["poster", "card"]],
  ["Soft Machine", "amaraok", "abstract", ["tshirt", "poster", "phonecase"]],
  ["Terrazzo Sunday", "sofiar", "illustration", ["sticker", "phonecase", "poster"]],
  ["Kinetic Grid", "noahb", "typography", ["poster", "tshirt"]],
  ["Nocturne", "yuwen", "minimal", ["poster", "card", "tshirt"]],
  ["Lagos Bloom", "amaraok", "illustration", ["tshirt", "poster", "sticker"]],
  ["Vessel Study 12", "elifk", "3d", ["print3d", "poster"]],
  ["Halftone Weather", "marcotv", "retro", ["poster", "sticker"]],
  ["Copenhagen Blue", "lenaost", "minimal", ["poster", "card"]],
  ["Ember Field", "kaisu", "abstract", ["tshirt", "poster"]],
  ["Type as Object", "noahb", "typography", ["poster", "card", "sticker"]],
  ["Sunday Terrace", "sofiar", "illustration", ["poster", "phonecase"]],
  ["Inkfall", "yuwen", "abstract", ["poster", "tshirt", "sticker"]],
  ["Orbital Drift", "kaisu", "geometric", ["poster", "phonecase", "print3d"]],
  ["Paper Cut No.7", "marcotv", "minimal", ["card", "poster"]],
  ["Prism Ritual", "amaraok", "abstract", ["tshirt", "sticker", "poster"]],
  ["Static Garden", "sofiar", "botanical", ["poster", "tshirt"]],
  ["Form Follows", "elifk", "3d", ["print3d", "poster", "card"]],
  ["Long Wave", "lenaost", "geometric", ["poster", "phonecase"]],
  ["Analog Ghost", "marcotv", "retro", ["tshirt", "sticker"]],
  ["Kanji Fragment", "yuwen", "typography", ["poster", "tshirt", "card"]],
  ["Deep Field", "kaisu", "abstract", ["poster", "phonecase"]],
  ["Bauhaus Sunday", "noahb", "geometric", ["poster", "sticker", "tshirt"]],
  ["Salt Flats", "lenaost", "minimal", ["poster", "card"]],
  ["Neon Verse", "amaraok", "abstract", ["tshirt", "phonecase"]],
  ["Cactus Grammar", "sofiar", "botanical", ["poster", "sticker"]],
  ["Modular Vase", "elifk", "3d", ["print3d"]],
  ["Contour Map 09", "kaisu", "minimal", ["poster", "card", "tshirt"]],
  ["Riso Dream", "marcotv", "retro", ["poster", "sticker", "phonecase"]],
  ["Grid Interrupted", "noahb", "typography", ["poster", "tshirt"]],
  ["Blue Hour", "yuwen", "minimal", ["poster", "phonecase", "card"]],
  ["Solar Bloom", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Lunar Grid", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Ember Field 02", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Cobalt Horizon", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Vermillion Signal", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Ivory Form", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Graphite Rhythm", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Terracotta Geometry", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Ultramarine Pattern", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Moss Wave", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Amber Orbit", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Slate Mosaic", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Crimson Gradient", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Sage Texture", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Indigo Composition", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Ochre Study", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Porcelain Series", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Obsidian Still Life", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Sand Landscape", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Electric Monolith", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Solar Bloom 02", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Lunar Grid 02", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Ember Field 03", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Cobalt Horizon 02", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Vermillion Signal 02", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Ivory Form 02", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Graphite Rhythm 02", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Terracotta Geometry 02", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Ultramarine Pattern 02", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Moss Wave 02", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Amber Orbit 02", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Slate Mosaic 02", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Crimson Gradient 02", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Sage Texture 02", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Indigo Composition 02", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Ochre Study 02", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Porcelain Series 02", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Obsidian Still Life 02", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Sand Landscape 02", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Electric Monolith 02", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Solar Bloom 03", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Lunar Grid 03", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Ember Field 04", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Cobalt Horizon 03", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Vermillion Signal 03", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Ivory Form 03", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Graphite Rhythm 03", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Terracotta Geometry 03", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Ultramarine Pattern 03", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Moss Wave 03", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Amber Orbit 03", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Slate Mosaic 03", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Crimson Gradient 03", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Sage Texture 03", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Indigo Composition 03", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Ochre Study 03", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Porcelain Series 03", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Obsidian Still Life 03", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Sand Landscape 03", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Electric Monolith 03", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Solar Bloom 04", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Lunar Grid 04", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Ember Field 05", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Cobalt Horizon 04", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Vermillion Signal 04", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Ivory Form 04", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Graphite Rhythm 04", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Terracotta Geometry 04", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Ultramarine Pattern 04", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Moss Wave 04", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Amber Orbit 04", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Slate Mosaic 04", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Crimson Gradient 04", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Sage Texture 04", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Indigo Composition 04", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Ochre Study 04", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Porcelain Series 04", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Obsidian Still Life 04", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Sand Landscape 04", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Electric Monolith 04", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Solar Bloom 05", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Lunar Grid 05", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Ember Field 06", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Cobalt Horizon 05", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Vermillion Signal 05", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Ivory Form 05", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Graphite Rhythm 05", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Terracotta Geometry 05", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Ultramarine Pattern 05", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Moss Wave 05", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Amber Orbit 05", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Slate Mosaic 05", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Crimson Gradient 05", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
  ["Sage Texture 05", "catalog", "typography", ["poster", "tshirt", "sticker"]],
  ["Indigo Composition 05", "catalog", "minimal", ["poster", "tshirt", "sticker"]],
  ["Ochre Study 05", "catalog", "retro", ["poster", "tshirt", "sticker"]],
  ["Porcelain Series 05", "catalog", "botanical", ["poster", "tshirt", "sticker"]],
  ["Obsidian Still Life 05", "catalog", "illustration", ["poster", "tshirt", "sticker"]],
  ["Sand Landscape 05", "catalog", "abstract", ["poster", "tshirt", "sticker"]],
  ["Electric Monolith 05", "catalog", "geometric", ["poster", "tshirt", "sticker"]],
];

const TAGPOOL = ["ai-generated", "print-ready", "vector", "editorial", "poster-art", "monochrome", "colorful", "gradient", "hand-drawn", "risograph", "swiss", "brutalist", "organic", "pattern"];

function seededRandom(seed: string) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return () => {
    h += 0x6D2B79F5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const DESIGNS: Design[] = RAW_DESIGNS.map((row, i) => {
  const r = seededRandom("design-" + row[0]);
  const adapters = row[3];
  const baseAdapter = adapterById(adapters[0]);
  if (!baseAdapter) throw new Error(`Seed design "${row[0]}" references unknown adapter "${adapters[0]}"`);
  // R2/H6: the premium is now part of the pricing formula, not a second, disconnected
  // "display price". Card price, listing price and charged price all derive from it.
  const premiumCents = Math.floor(r() * 14) * 100;
  return {
    id: "dsg_" + String(1042 + i),
    slug: row[0].toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    seed: row[0],
    title: row[0],
    creator: row[1],
    category: row[2],
    adapters: adapters,
    premiumCents,
    priceCents: baseAdapter.retailCents + premiumCents,
    likes: 60 + Math.floor(r() * 3200),
    views: 900 + Math.floor(r() * 48000),
    sales: 4 + Math.floor(r() * 420),
    rating: parseFloat((4.3 + r() * 0.7).toFixed(1)),
    reviews: 3 + Math.floor(r() * 180),
    aiGenerated: r() > 0.45,
    isNew: i % 7 === 3,
    tags: [TAGPOOL[i % TAGPOOL.length], TAGPOOL[(i * 3 + 5) % TAGPOOL.length], row[2]],
    created: ["2 hours", "6 hours", "1 day", "2 days", "4 days", "1 week", "2 weeks", "3 weeks"][i % 8] + " ago",
    palette: PALETTES[i % PALETTES.length],
    shape: i % 6,
  };
});

/** Strict lookups — return `undefined` when there is no match (no silent fallback). */
export const designById = (id: string): Design | undefined => DESIGNS.find((d) => d.id === id);
export const designBySlug = (slug: string): Design | undefined => DESIGNS.find((d) => d.slug === slug);
export const designsByCreator = (h: string): Design[] => DESIGNS.filter((d) => d.creator === h);

/**
 * Order lifecycle states. Must stay in sync with the server-side status machine in
 * `src/app/api/orders/[id]/route.ts` — R2/M7: `routing` was missing here while the
 * API emitted it on every new order, so freshly placed orders rendered an unlabelled badge.
 */
export const ORDER_STATES = [
  { id: "paid", label: "Paid", tone: "moss" },
  { id: "routing", label: "Routing", tone: "cobalt" },
  { id: "in_production", label: "In production", tone: "amber" },
  { id: "quality_check", label: "Quality check", tone: "cobalt" },
  { id: "shipped", label: "Shipped", tone: "violet" },
  { id: "delivered", label: "Delivered", tone: "moss" },
  { id: "exception", label: "Needs attention", tone: "signal" },
];

// R2/H5: the hard-coded `ORDERS` seed array was removed. It was rendered on /orders
// whenever the signed-in user had zero real orders, showing five fabricated orders
// (with invented factories, ETAs and tracking numbers) that all 404'd when clicked.
// Order data now comes exclusively from GET /api/orders.

export const money = (cents: number, cur = "$"): string => {
  if (!Number.isFinite(cents)) return cur + "0.00";
  const neg = cents < 0;
  const v = Math.abs(cents) / 100;
  return (neg ? "-" + cur : cur) + v.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};

export const compact = (n: number): string => {
  if (!Number.isFinite(n)) return "0";
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1).replace(/\.0$/, "") + "M";
  if (n >= 1000) return (n / 1000).toFixed(n >= 10000 ? 0 : 1).replace(/\.0$/, "") + "k";
  return String(n);
};

// ============================================================
// Pricing — single source of truth (shared by client + server)
// ============================================================

/**
 * The variant catalog is the single source of truth for BOTH the UI selector and the
 * price delta. R2/M4+M5: this used to be two disconnected pieces of code — a hard-coded
 * list in the listing page plus substring matching in the pricing function. That combo
 * meant `"L · Black"` never got its $1.00 upcharge (the pattern was `"l "` with a
 * trailing space, which `"l · black"` does not contain) while any attacker-supplied
 * string containing `"xl"` did. Exact matching against this catalog fixes both.
 */
export const ADAPTER_VARIANTS: Record<string, ReadonlyArray<{ id: string; deltaCents: number }>> = {
  tshirt: [
    { id: "S · White", deltaCents: 0 },
    { id: "M · White", deltaCents: 0 },
    { id: "L · White", deltaCents: 100 },
    { id: "M · Black", deltaCents: 0 },
    { id: "L · Black", deltaCents: 100 },
    { id: "XL · Black", deltaCents: 250 },
    { id: "M · Bone", deltaCents: 0 },
  ],
  poster: [
    { id: "A3", deltaCents: 0 },
    { id: "A2", deltaCents: 400 },
    { id: "50×70cm", deltaCents: 500 },
    { id: "70×100cm", deltaCents: 800 },
  ],
  card: [
    { id: "Standard · 3.5×2", deltaCents: 0 },
    { id: "Square · 2.5×2.5", deltaCents: 200 },
    { id: "Rounded", deltaCents: 200 },
  ],
  phonecase: [
    { id: "iPhone 15", deltaCents: 0 },
    { id: "iPhone 15 Pro", deltaCents: 0 },
    { id: "Pixel 9", deltaCents: 0 },
    { id: "Galaxy S24", deltaCents: 0 },
  ],
  sticker: [
    { id: "Gloss", deltaCents: 0 },
    { id: "Matte", deltaCents: 0 },
    { id: "Holographic", deltaCents: 0 },
    { id: "Vinyl", deltaCents: 0 },
  ],
  print3d: [
    { id: "PLA · Ivory", deltaCents: 0 },
    { id: "PLA · Black", deltaCents: 0 },
    { id: "Resin · White", deltaCents: 900 },
    { id: "PLA · Terracotta", deltaCents: 0 },
  ],
};

/** Selectable variants for an adapter (UI). Empty array for an unknown adapter. */
export function variantsFor(adapterId: string): string[] {
  return (ADAPTER_VARIANTS[adapterId] ?? []).map((v) => v.id);
}

/**
 * Extra cost in cents for a product variant.
 * Returns `null` when the adapter is unknown or the variant is not in its catalog —
 * callers MUST treat `null` as "reject this line", never as zero.
 */
export function variantDeltaCents(adapterId: string, variant: string): number | null {
  const catalog = ADAPTER_VARIANTS[adapterId];
  if (!catalog) return null;
  const hit = catalog.find((v) => v.id === variant);
  return hit ? hit.deltaCents : null;
}

/**
 * The one authoritative unit price: adapter base + creator premium + variant delta.
 * Returns `null` for an unknown adapter or an out-of-catalog variant.
 *
 * R2/C4+H6: `design` is now genuinely used. Previously it was accepted and ignored,
 * while `Design.priceCents` carried a second, unrelated randomly-generated price —
 * so the same product showed three different amounts across card, listing and receipt.
 */
export function unitPriceCents(
  design: Pick<Design, "premiumCents">,
  adapterId: string,
  variant = "",
): number | null {
  const a = adapterById(adapterId);
  if (!a) return null;
  // 空 variant（未选规格）按基准价计，delta=0；非空的未知 variant 才拒绝（返回 null）。
  const delta = variant ? variantDeltaCents(adapterId, variant) : 0;
  if (delta === null) return null;
  return a.retailCents + design.premiumCents + delta;
}

export type TotalsLine = { priceCents: number; qty: number };

export interface Totals {
  subtotalCents: number;
  shippingCents: number;
  taxCents: number;
  totalCents: number;
  freeShipping: boolean;
}

/** One pricing formula for the whole app (cart, checkout, API). */
export function computeTotals(lines: TotalsLine[]): Totals {
  const subtotal = lines.reduce((s, l) => s + Math.max(0, l.priceCents) * Math.max(0, l.qty), 0);
  const freeShipping = subtotal === 0 || subtotal >= 5000;
  const shipping = freeShipping ? 0 : 499; // free over $50
  const tax = Math.round(subtotal * 0.08); // 8% estimated tax
  return {
    subtotalCents: subtotal,
    shippingCents: shipping,
    taxCents: tax,
    totalCents: subtotal + shipping + tax,
    freeShipping,
  };
}

export const HERO_STATS = [
  { v: "128,400", k: "Designs live" },
  { v: "6", k: "Adapters" },
  { v: "2,481", k: "Jobs printing now" },
  { v: "4m 12s", k: "Avg. publish time" },
];

// ============================================================
// M3: SKU 级报价引擎（替代写死的 adapter.retailCents）
// ============================================================
//
// 每件商品的售价 = 该 SKU 的建议零售价（来自 pricing.ts 真实供应链成本）+ variant 增量。
// 创作者 royalty 是售价之上的"分成比例"，不抬高售价（区别于 premiumCents）。

/** family → 该 family 的代表性适配器 id（variant 增量表以 adapter id 为键） */
const FAMILY_TO_ADAPTER: Record<FamilyId, string> = (() => {
  const m = {} as Record<FamilyId, string>;
  for (const a of ADAPTERS) if (!m[a.family]) m[a.family] = a.id;
  return m;
})();

/** SKU → 所属 family */
export function familyOfSku(sku: string): FamilyId | undefined {
  return SKU_BY_ID[sku]?.family;
}

/** SKU → 该 family 的代表性适配器 id（用于兼容仅认 adapter 的旧逻辑/UI） */
export function adapterIdForSku(sku: string): string | undefined {
  const fam = familyOfSku(sku);
  return fam ? FAMILY_TO_ADAPTER[fam] : undefined;
}

/**
 * M5: 某 SKU 可选的 variant 列表。
 * family=home 的 SKU（马克杯 / 抱枕 / 毛毯 / 玻璃杯…）映射到的代表适配器是 `print3d`，
 * 但它的 variant 是「PLA · Ivory / Resin · White」这类 3D 打印耗材，套到马克杯上毫无意义，
 * 所以 home 系一律不提供 variant（下单时 variant 传空串即可）。
 */
export function variantsForSku(sku: string): string[] {
  const fam = familyOfSku(sku);
  if (!fam || fam === "home") return [];
  const adapterId = FAMILY_TO_ADAPTER[fam];
  return adapterId ? variantsFor(adapterId) : [];
}

/** 某 SKU 在某 variant 下的增量（cents）；未知 family/adapter 或非法 variant 返回 null */
export function variantDeltaForSku(sku: string, variant: string): number | null {
  const fam = familyOfSku(sku);
  if (!fam) return null;
  const adapterId = FAMILY_TO_ADAPTER[fam];
  if (!adapterId) return null;
  return variantDeltaCents(adapterId, variant);
}

/** SKU + variant 的系统报价（cents，不含税）。未知 SKU 返回 null。 */
export function unitPriceForSku(sku: string, variant = ""): number | null {
  const p = SKU_BY_ID[sku];
  if (!p) return null;
  const delta = variant ? variantDeltaForSku(sku, variant) : 0;
  if (delta === null) return null;
  return skuRetailCents(p) + delta;
}

/**
 * 目的地 → 税率档位（决策 #4：EU 19% / US 7% / 其他 0%）。
 * 平台代缴，计入售价，不进分成基数。
 */
const EU_COUNTRIES = new Set([
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE",
  "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE", "GB",
  "CH", "NO", "IS",
]);

export function regionFromCountry(country?: string): Region {
  if (!country) return "DEFAULT";
  const c = country.trim().toUpperCase();
  if (c === "US" || c === "USA" || c === "UNITED STATES") return "US";
  if (EU_COUNTRIES.has(c)) return "EU";
  return "DEFAULT";
}

export interface OrderSkuLine {
  sku: string;
  qty: number;
  variant?: string;
}

/**
 * 订单级总价（决策 #3/#4）：
 *  - 商品小计 = Σ 每件 (salePrice = retail×(1+tax) + variant增量) × qty（含平台代缴税，计入售价）
 *  - 运费 = 按各 line 重量级首件全价 + 续件递减（skuOrderFreightUSD）
 *  - 税费（展示用）= 小计 − 不含税小计（平台代缴，不进分成基数）
 *  - total = 小计 + 运费
 */
export function computeOrderTotals(lines: OrderSkuLine[], region: Region = "DEFAULT"): Totals {
  let retailSubtotal = 0; // 不含税货值
  let saleSubtotal = 0; // 含税货值（实际收取）
  const freightLines: { sku: string; qty: number }[] = [];

  for (const l of lines) {
    const p = SKU_BY_ID[l.sku];
    if (!p || l.qty <= 0) continue;
    const delta = l.variant ? variantDeltaForSku(l.sku, l.variant) : 0;
    if (delta === null) continue;
    retailSubtotal += (skuRetailCents(p) + delta) * l.qty;
    saleSubtotal += (skuSaleCents(p, region) + delta) * l.qty;
    freightLines.push({ sku: l.sku, qty: l.qty });
  }

  const shippingCents = Math.round(skuOrderFreightUSD(freightLines) * 100);
  const taxCentsTotal = saleSubtotal - retailSubtotal;
  return {
    subtotalCents: saleSubtotal,
    shippingCents,
    taxCents: taxCentsTotal,
    totalCents: saleSubtotal + shippingCents,
    freeShipping: shippingCents === 0,
  };
}
